name: CI

on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install
        run: yarn install --frozen-lockfile --non-interactive --prefer-offline
      - name: Check types
        run: yarn run typecheck
      - name: Lint
        run: yarn run lint
